services:
  - type: web
    name: neighbourhood-board
    runtime: go
    rootDir: .
    buildCommand: go mod download && go build -tags netgo -ldflags '-s -w' -o app ./cmd/main.go
    startCommand: ./app
    envVars:
      - key: PORT
        value: 8080
      - key: DB_PATH
        value: /data/bulletin.db
      - key: CGO_ENABLED
        value: "0"
      - key: GOFLAGS
        value: "-mod=mod"
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
