services:
  - type: web
    name: neighbourhood-board
    runtime: go
    rootDir: .
    buildCommand: go mod tidy && go build -tags netgo -ldflags '-s -w' -o app ./cmd/main.go
    startCommand: ./app
    envVars:
      - key: PORT
        value: 8080
      - key: CGO_ENABLED
        value: "0"
      - key: GOFLAGS
        value: "-mod=mod"
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
